// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWfktSdOvohMK-43XLROxi6LHY6RHWnw',
    appId: '1:240961413878:web:29c8e0f7aabfa87ded42d7',
    messagingSenderId: '240961413878',
    projectId: 'schedule-228e7',
    authDomain: 'schedule-228e7.firebaseapp.com',
    databaseURL: 'https://schedule-228e7-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-228e7.firebasestorage.app',
    measurementId: 'G-F17D19HBMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Svb0GDTOExf5IPhxRgLLz1g2qOBaPMQ',
    appId: '1:240961413878:android:aa2df8e7ec3200e5ed42d7',
    messagingSenderId: '240961413878',
    projectId: 'schedule-228e7',
    databaseURL: 'https://schedule-228e7-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-228e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1dFIkPdlCSdFjHHEr6ipgrTxrj0IN4w',
    appId: '1:240961413878:ios:bd9d6eea427ff06fed42d7',
    messagingSenderId: '240961413878',
    projectId: 'schedule-228e7',
    databaseURL: 'https://schedule-228e7-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-228e7.firebasestorage.app',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1dFIkPdlCSdFjHHEr6ipgrTxrj0IN4w',
    appId: '1:240961413878:ios:bd9d6eea427ff06fed42d7',
    messagingSenderId: '240961413878',
    projectId: 'schedule-228e7',
    databaseURL: 'https://schedule-228e7-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-228e7.firebasestorage.app',
    iosBundleId: 'com.example.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZWfktSdOvohMK-43XLROxi6LHY6RHWnw',
    appId: '1:240961413878:web:50f47834417a1246ed42d7',
    messagingSenderId: '240961413878',
    projectId: 'schedule-228e7',
    authDomain: 'schedule-228e7.firebaseapp.com',
    databaseURL: 'https://schedule-228e7-default-rtdb.firebaseio.com',
    storageBucket: 'schedule-228e7.firebasestorage.app',
    measurementId: 'G-GDQG1JN1B9',
  );

}